version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: tienda_bts
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"   
    volumes:
      - "./mysql/:/var/lib/mysql"  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"   
    environment:
      MYSQL_ROOT_PASSWORD: 
      PMA_HOST: db     
      PMA_USER: root
      PMA_PASSWORD: 
